# Generated by Django 4.2.4 on 2023-09-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='your_domain',
            field=models.URLField(default='localhost', null=True),
        ),
    ]
