# Generated by Django 4.2.4 on 2023-09-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_config_your_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='your_domain',
            new_name='daas_provider_baseurl',
        ),
    ]
