# Generated by Django 4.2.4 on 2023-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_your_domain_config_daas_provider_baseurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='daas_provider_baseurl',
            field=models.CharField(default='localhost', max_length=200, null=True),
        ),
    ]
